# Stage 1: Build the application
FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/lms ./
RUN npm ci
RUN npm run build

# Stage 2: Serve the application
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV=development \
    PORT=3000 \
    HOSTNAME="0.0.0.0"

COPY --from=build /app/public ./public
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
