"""Update - book의 book_manage_id를 유니크하게 변경

Revision ID: cf55aacbed57
Revises: a7fa582fd6fb
Create Date: 2025-04-03 13:51:56.266875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf55aacbed57'
down_revision: Union[str, None] = 'a7fa582fd6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_book_manage_id', table_name='books')
    op.create_index(op.f('ix_books_book_manage_id'), 'books', ['book_manage_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_book_manage_id'), table_name='books')
    op.create_index('ix_books_book_manage_id', 'books', ['book_manage_id'], unique=False)
    # ### end Alembic commands ###
